### ISSUE TITLE
CSS属性声明顺序

### ISSUE THREAD

**Issue by shuangmianxiaoQ** [shuangmianxiaoQ/myblog#4]
**本文首发于 [双面小Q - 简书](https://www.jianshu.com/p/03216f409516)**

> 本文参考：
> [Code Guide by @AlloyTeam](http://alloyteam.github.io/CodeGuide/#css-declaration-order)

------

### 推荐顺序

属性声明按下面的顺序做分组处理，组与租之间需要有一个空行

``` css
/* 常用css属性声明示例 */
.declaration-order {
    display: block;
    visibility: hidden;
    float: left;
    clear: both;
    over-flow: auto;
    zoom: 1;

    border-spacing: 1px;
    list-style: none;

    position: absolute;
    top: 0;
    right: 0;
    bottom: 0;
    left: 0;
    z-index: 100;

    margin: 0 auto;
    box-sizing: border-box;
    border: 1px solid #ccc;
    border-radius: 4px;
    padding: 15px;
    width: 500px;
    min-width: 200px;
    max-width: 500px;
    height: 300px;

    font: italic bolder 16px/3 cursive;
    font-family: sans-serif;
    font-size: 14px;
    font-weight: border;
    font-style: italic;
    line-height: 1.5em;
    text-align: center;
    vertical-align: middle;
    white-space: nowrap;
    text-decoration: underline;
    text-indent: 2em;
    letter-spacing: 4px;
    word-spacing: 2px;
    text-transform: capitalize;
    text-overflow: ellipsis;
    word-break: break-all;

    color: #fff;
    background: #f0f0f0;
    background-color: #eee;
    background-image: url('**.png');
    background-repeat: no-repeat;
    background-attachment: scroll;
    background-position: 10px 20px;
    background-origin:content-box;
    background-size:80px 60px;

    outline: none;
    opacity: .5;
    box-shadow: 10px 5px 5px #ddd;
    text-shadow: 1px 1px 2px #333;

    transition: all 3s ease-out 1s;
    transform: scale(2, 0.5);
    animation: 3s linear 1s slidein;
    
    content: '';
    cursor: pointer;
}
```
